---
- hosts: rails
  vars:
    branch: 'master'
    dest: '{{ ansible_env.HOME }}/{{ project }}'
    unicorn_pid: '{{ dest }}/tmp/pids/unicorn.pid'
    rails_env: 'production'
    colon: ':'
    env:
      RAILS_ENV: '{{ rails_env }}'
      PATH: '{{ ansible_env.HOME }}/.rbenv/shims:{{ ansible_env.PATH }}'
  tasks:
    - include: tasks/iptables.yml
    - include: tasks/git.yml
    - include: tasks/ruby.yml
    - include: tasks/mysql.yml
    - include: tasks/bundle.yml
    - include: tasks/nginx.yml
    - include: tasks/unicorn.yml
    - include: tasks/database.yml
    - include: tasks/assets.yml
    - include: tasks/service.yml
  handlers:
    - name: restart iptables
      service: name=iptables state=restarted
