---
- name: gem bundler install
  shell: /bin/bash -lc "gem install bundler"

- name: bundle install
  shell: /bin/bash -lc "bundle config build.nokogiri --use-system-libraries && bundle install --without test development"
  args:
    chdir: "{{ dest }}"