---
- name: install mysql
  yum: name=mysql-server state=latest

- name: install mysql
  yum: name=mysql-devel state=latest

- name: start mysql
  service:
    name=mysqld
    enabled=yes
    state=started
  sudo: yes
