---
- name: install the nginx rpm from a remote repo
  yum: name=http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm state=present

- name: install nginx
  yum: name=nginx state=latest

- name: default nginx conf backup
  shell: mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf.bak
  ignore_errors: yes

- name: copy nginx unicorn conf
  template: 
    src=unicorn-app.nginx.j2
    dest=/etc/nginx/conf.d/unicorn-app.conf
    owner=root
    group=root
    mode=0644

- name: set nginx user
  replace:
    dest=/etc/nginx/nginx.conf
    regexp='^user  nginx;$'
    replace='user  root;'
 